//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("shrink ver:1.4.21127.1")]
[assembly: AssemblyDescription("shrinks the current console window to 80 columns by 25 rows.")]
[assembly: AssemblyCompany("Bricksoft.com")]
[assembly: AssemblyProduct("shrink")]
[assembly: AssemblyCopyright("Copyright (C) 2010-2012 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("594CA055-3BF8-47EC-B5C1-F8B57390396C")]
[assembly: AssemblyVersion("1.4.21127.1")]
[assembly: AssemblyFileVersion("1.4.21127.1")]


